import type { Metadata } from "next";
import { LegalPage } from "@/components/shared/LegalPage";

export const metadata: Metadata = {
  title: "Privacy Policy | Medical Key",
  description: "How Medical Key collects, uses, and protects your personal information.",
};

export default function PrivacyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      updatedOn="1 August 2026"
      intro="Your privacy matters to us. This Privacy Policy explains what information we collect, how we use it, and the choices you have. This is placeholder content for demonstration purposes and should be replaced with a policy reviewed by legal counsel before launch."
      sections={[
        {
          heading: "1. Information We Collect",
          body: (
            <p>
              We collect information you provide directly — such as your name, contact details,
              date of birth, and medical preferences — as well as information generated by your
              use of the platform, like appointment history and order details.
            </p>
          ),
        },
        {
          heading: "2. How We Use Your Information",
          body: (
            <p>
              We use your information to facilitate bookings, process payments, send
              appointment reminders, provide customer support, and improve our services.
            </p>
          ),
        },
        {
          heading: "3. Sharing With Third Parties",
          body: (
            <p>
              We share relevant details with the doctor, hospital, lab, or pharmacy you book
              with, and with payment and delivery partners as needed to complete your request.
              We do not sell your personal data to advertisers.
            </p>
          ),
        },
        {
          heading: "4. Data Security",
          body: (
            <p>
              We use industry-standard security measures, including encryption in transit, to
              protect your information. No system is completely secure, and we encourage you to
              use a strong, unique password for your account.
            </p>
          ),
        },
        {
          heading: "5. Your Choices",
          body: (
            <p>
              You can access, update, or request deletion of your personal information at any
              time from your account settings or by contacting our support team.
            </p>
          ),
        },
        {
          heading: "6. Contact Us",
          body: (
            <p>
              Questions about this policy can be directed to support@medicalkey.in or through
              our Contact page.
            </p>
          ),
        },
      ]}
    />
  );
}
